# Generated by Django 4.1.4 on 2023-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_genre_options_alter_publisher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sub_title',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
