# Generated by Django 4.1.4 on 2023-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
