# Generated by Django 4.1.4 on 2023-01-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
