# Generated by Django 4.1.4 on 2023-01-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='counter',
        ),
    ]
