# Generated by Django 4.1.4 on 2023-01-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_book_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
