# Generated by Django 4.1.4 on 2023-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_book_genre_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='images/no_images.png', null=True, upload_to='images/'),
        ),
    ]
