# Generated by Django 4.1.4 on 2023-01-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book'},
        ),
    ]
